### PR TITLE
Use a better weak map implementation

### PR DESCRIPTION
**Pull request by mattdesl**
The current weakmap implementation is really horrifying (using eval, trying to parse function names, etc). It seems to be no longer maintained.

It also breaks in CocoonJS, and in Safari 7.0.3 after UglifyJS (mangle + compress) because of the strange crap it's using. 

This is a drop in change to use [weak-map](https://www.npmjs.org/package/weak-map), which fixes these problems and seems to work fine for all the demos I've tested so far. Hopefully it can come in a patch to ease the upgrade across all the dozens of modules that rely on webglew in one way or another.

### CODE REVIEW

**Comment by hughsk** [comment]
@mattdesl oh wow, good catch! Thanks man, will merge this in and make it a patch release.

It's worth noting that `weak-map` will leak memory if WeakMaps aren't supported natively. I think this should be OK with the way it's being used now: a per-context cache, when there's generally never more than 1 context. WeakMaps have also already landed in Chrome, and I think Firefox too :tada:

**Comment by hughsk** [comment]
@mattdesl published, `webglew@1.0.5`. Let me know if any of the dependent packages need updating :)

**Comment by mikolalysenko** [comment]
Whoa!  Thanks for catching this!

I think that weakmap is being used in a couple more places.  Maybe we should send the maintainer of that repo a message and see if they can fix it?  (Or alternatively, maybe they can transfer ownership to someone who does care?)

**Comment by mattdesl** [comment]
Worth a shot. I posted an issue in October but haven't heard anything back.

https://github.com/Benvie/WeakMap/issues/10

**Pull request merged**
